#!/bin/bash

set -x

version_info_line=$(cat ./gradle.properties |grep --color=never 'latestReleasedVersion=')
version_info_line=(${version_info_line//=/ })
version=${version_info_line[1]}

read -p "Version is “$version”. Stop this script if that’s not OK."

version_suffixed=$version-defused
path_to_project_in_target="~/Desktop/.remote/dart/flutterfire/packages/firebase_messaging/firebase_messaging"
path_to_aars_in_target="$path_to_project_in_target/example/android/app/local_aars/com/google/firebase"

../gradlew clean &&
../gradlew assembleRelease &&
ssh $WIN " \
    cd $path_to_aars_in_target &&
    rm -rf firebase-messaging &&
    mkdir firebase-messaging &&
    mkdir firebase-messaging/$version_suffixed" &&
scp build/outputs/aar/*.aar $WIN:$path_to_aars_in_target/firebase-messaging/$version_suffixed/firebase-messaging-$version_suffixed.aar &&
ssh $WIN " \
    cd $path_to_project_in_target &&
    ./patch_pom_files.sh $version"
